if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
 # target_sources(main PRIVATE gui_linux.cpp)
    message("Linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
#  target_sources(main PRIVATE gui_windows.cpp)
    message("Windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
#   target_sources(main PRIVATE gui_macos.cpp)
    message("Darwin")
else()
    message(FATAL_ERROR "CMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME} not supported.")
endif()